name: Docker Promote

on:
  push:
    tags:
      - "*"

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/github-action-docker-promote@0.3.0
        id: promote
        with:
          registry: ghcr.io
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          login: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          platforms: linux/amd64,linux/arm64
          from: sha-${{ github.sha }}
          to: ${{ github.event.release.tag_name }}
          use_metadata: false